<?php 
$this->headTitle("Till Receipt");
?>

<table>

<tr>
    <th><?php echo $this->translate("Item(s)");?></th>
    <th>|</th>
    <th><?php echo $this->translate("Price");?></th>
</tr>

	<?php if(!$this->noItem) { ?>

<?php foreach($this->itemlist as $item) :?>
 <tr>
<td><?php echo $item['name'];?></td>
<td>|</td>
<td><?php echo $this->currency."  ".$item['price']; ?></td>
</tr>

<?php  endforeach;?>

<tr><td colspan=3>---------------------------------------------------------</td><tr>

	<tr>
<td><?php echo $this->translate("Sub Total");?></td>
<td>|</td>
<td><?php echo $this->currency."  ".$this->subTotal; ?></td>
</tr>

<tr>
<td><?php echo $this->translate("Discount");?></td>
<td>|</td>
<td><?php echo $this->currency."  ".$this->discount; ?></td>
</tr>


<tr><td colspan=3>---------------------------------------------------------</td><tr>
<tr>
<td><?php echo $this->translate("Grand Total");?></td>
<td>|</td>
<td><?php echo $this->currency."  ".$this->grandTotal; ?></td>
</tr>

<?php 
}
else
{
?>
<tr><td >------------No Item Found-------------</td><tr>
<?php
}
?>
</table>


